const mockPokemonAttributes = [
    {
      "id": 1,
      "name": "bulbasaur",
      "height": 7,
      "weight": 69,
      "type1": "grass",
      "type2": "poison",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/1.svg",
      "color": "green",
      "habitat": "grassland"
    },
    {
      "id": 2,
      "name": "ivysaur",
      "height": 10,
      "weight": 130,
      "type1": "grass",
      "type2": "poison",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg",
      "color": "green",
      "habitat": "grassland"
    },
    {
      "id": 3,
      "name": "venusaur",
      "height": 20,
      "weight": 1000,
      "type1": "grass",
      "type2": "poison",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/3.svg",
      "color": "green",
      "habitat": "grassland"
    },
    {
      "id": 4,
      "name": "charmander",
      "height": 6,
      "weight": 85,
      "type1": "fire",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/4.svg",
      "color": "red",
      "habitat": "mountain"
    },
    {
      "id": 5,
      "name": "charmeleon",
      "height": 11,
      "weight": 190,
      "type1": "fire",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/5.svg",
      "color": "red",
      "habitat": "mountain"
    },
    {
      "id": 6,
      "name": "charizard",
      "height": 17,
      "weight": 905,
      "type1": "fire",
      "type2": "flying",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/6.svg",
      "color": "red",
      "habitat": "mountain"
    },
    {
      "id": 7,
      "name": "squirtle",
      "height": 5,
      "weight": 90,
      "type1": "water",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/7.svg",
      "color": "blue",
      "habitat": "waters-edge"
    },
    {
      "id": 8,
      "name": "wartortle",
      "height": 10,
      "weight": 225,
      "type1": "water",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/8.svg",
      "color": "blue",
      "habitat": "waters-edge"
    },
    {
      "id": 9,
      "name": "blastoise",
      "height": 16,
      "weight": 855,
      "type1": "water",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/9.svg",
      "color": "blue",
      "habitat": "waters-edge"
    },
    {
      "id": 10,
      "name": "caterpie",
      "height": 3,
      "weight": 29,
      "type1": "bug",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/10.svg",
      "color": "green",
      "habitat": "forest"
    },
    {
      "id": 11,
      "name": "metapod",
      "height": 7,
      "weight": 99,
      "type1": "bug",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/11.svg",
      "color": "green",
      "habitat": "forest"
    },
    {
      "id": 12,
      "name": "butterfree",
      "height": 11,
      "weight": 320,
      "type1": "bug",
      "type2": "flying",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/12.svg",
      "color": "white",
      "habitat": "forest"
    },
    {
      "id": 13,
      "name": "weedle",
      "height": 3,
      "weight": 32,
      "type1": "bug",
      "type2": "poison",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/13.svg",
      "color": "brown",
      "habitat": "forest"
    },
    {
      "id": 14,
      "name": "kakuna",
      "height": 6,
      "weight": 100,
      "type1": "bug",
      "type2": "poison",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/14.svg",
      "color": "yellow",
      "habitat": "forest"
    },
    {
      "id": 15,
      "name": "beedrill",
      "height": 10,
      "weight": 295,
      "type1": "bug",
      "type2": "poison",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/15.svg",
      "color": "yellow",
      "habitat": "forest"
    },
    {
      "id": 16,
      "name": "pidgey",
      "height": 3,
      "weight": 18,
      "type1": "normal",
      "type2": "flying",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/16.svg",
      "color": "brown",
      "habitat": "forest"
    },
    {
      "id": 17,
      "name": "pidgeotto",
      "height": 11,
      "weight": 300,
      "type1": "normal",
      "type2": "flying",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/17.svg",
      "color": "brown",
      "habitat": "forest"
    },
    {
      "id": 18,
      "name": "pidgeot",
      "height": 15,
      "weight": 395,
      "type1": "normal",
      "type2": "flying",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/18.svg",
      "color": "brown",
      "habitat": "forest"
    },
    {
      "id": 19,
      "name": "rattata",
      "height": 3,
      "weight": 35,
      "type1": "normal",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/19.svg",
      "color": "purple",
      "habitat": "grassland"
    },
    {
      "id": 20,
      "name": "raticate",
      "height": 7,
      "weight": 185,
      "type1": "normal",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/20.svg",
      "color": "brown",
      "habitat": "grassland"
    },
    {
      "id": 21,
      "name": "spearow",
      "height": 3,
      "weight": 20,
      "type1": "normal",
      "type2": "flying",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/21.svg",
      "color": "brown",
      "habitat": "rough-terrain"
    },
    {
      "id": 22,
      "name": "fearow",
      "height": 12,
      "weight": 380,
      "type1": "normal",
      "type2": "flying",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/22.svg",
      "color": "brown",
      "habitat": "rough-terrain"
    },
    {
      "id": 23,
      "name": "ekans",
      "height": 20,
      "weight": 69,
      "type1": "poison",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/23.svg",
      "color": "purple",
      "habitat": "grassland"
    },
    {
      "id": 24,
      "name": "arbok",
      "height": 35,
      "weight": 650,
      "type1": "poison",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/24.svg",
      "color": "purple",
      "habitat": "grassland"
    },
    {
      "id": 25,
      "name": "pikachu",
      "height": 4,
      "weight": 60,
      "type1": "electric",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/25.svg",
      "color": "yellow",
      "habitat": "forest"
    },
    {
      "id": 26,
      "name": "raichu",
      "height": 8,
      "weight": 300,
      "type1": "electric",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/26.svg",
      "color": "yellow",
      "habitat": "forest"
    },
    {
      "id": 27,
      "name": "sandshrew",
      "height": 6,
      "weight": 120,
      "type1": "ground",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/27.svg",
      "color": "yellow",
      "habitat": "rough-terrain"
    },
    {
      "id": 28,
      "name": "sandslash",
      "height": 10,
      "weight": 295,
      "type1": "ground",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/28.svg",
      "color": "yellow",
      "habitat": "rough-terrain"
    },
    {
      "id": 29,
      "name": "nidoran-f",
      "height": 4,
      "weight": 70,
      "type1": "poison",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/29.svg",
      "color": "blue",
      "habitat": "grassland"
    },
    {
      "id": 30,
      "name": "nidorina",
      "height": 8,
      "weight": 200,
      "type1": "poison",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/30.svg",
      "color": "blue",
      "habitat": "grassland"
    },
    {
      "id": 31,
      "name": "nidoqueen",
      "height": 13,
      "weight": 600,
      "type1": "poison",
      "type2": "ground",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/31.svg",
      "color": "blue",
      "habitat": "grassland"
    },
    {
      "id": 32,
      "name": "nidoran-m",
      "height": 5,
      "weight": 90,
      "type1": "poison",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/32.svg",
      "color": "purple",
      "habitat": "grassland"
    },
    {
      "id": 33,
      "name": "nidorino",
      "height": 9,
      "weight": 195,
      "type1": "poison",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/33.svg",
      "color": "purple",
      "habitat": "grassland"
    },
    {
      "id": 34,
      "name": "nidoking",
      "height": 14,
      "weight": 620,
      "type1": "poison",
      "type2": "ground",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/34.svg",
      "color": "purple",
      "habitat": "grassland"
    },
    {
      "id": 35,
      "name": "clefairy",
      "height": 6,
      "weight": 75,
      "type1": "fairy",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/35.svg",
      "color": "pink",
      "habitat": "mountain"
    },
    {
      "id": 36,
      "name": "clefable",
      "height": 13,
      "weight": 400,
      "type1": "fairy",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/36.svg",
      "color": "pink",
      "habitat": "mountain"
    },
    {
      "id": 37,
      "name": "vulpix",
      "height": 6,
      "weight": 99,
      "type1": "fire",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/37.svg",
      "color": "brown",
      "habitat": "grassland"
    },
    {
      "id": 38,
      "name": "ninetales",
      "height": 11,
      "weight": 199,
      "type1": "fire",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/38.svg",
      "color": "yellow",
      "habitat": "grassland"
    },
    {
      "id": 39,
      "name": "jigglypuff",
      "height": 5,
      "weight": 55,
      "type1": "normal",
      "type2": "fairy",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/39.svg",
      "color": "pink",
      "habitat": "grassland"
    },
    {
      "id": 40,
      "name": "wigglytuff",
      "height": 10,
      "weight": 120,
      "type1": "normal",
      "type2": "fairy",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/40.svg",
      "color": "pink",
      "habitat": "grassland"
    },
    {
      "id": 41,
      "name": "zubat",
      "height": 8,
      "weight": 75,
      "type1": "poison",
      "type2": "flying",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/41.svg",
      "color": "purple",
      "habitat": "cave"
    },
    {
      "id": 42,
      "name": "golbat",
      "height": 16,
      "weight": 550,
      "type1": "poison",
      "type2": "flying",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/42.svg",
      "color": "purple",
      "habitat": "cave"
    },
    {
      "id": 43,
      "name": "oddish",
      "height": 5,
      "weight": 54,
      "type1": "grass",
      "type2": "poison",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/43.svg",
      "color": "blue",
      "habitat": "grassland"
    },
    {
      "id": 44,
      "name": "gloom",
      "height": 8,
      "weight": 86,
      "type1": "grass",
      "type2": "poison",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/44.svg",
      "color": "blue",
      "habitat": "grassland"
    },
    {
      "id": 45,
      "name": "vileplume",
      "height": 12,
      "weight": 186,
      "type1": "grass",
      "type2": "poison",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/45.svg",
      "color": "red",
      "habitat": "grassland"
    },
    {
      "id": 46,
      "name": "paras",
      "height": 3,
      "weight": 54,
      "type1": "bug",
      "type2": "grass",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/46.svg",
      "color": "red",
      "habitat": "forest"
    },
    {
      "id": 47,
      "name": "parasect",
      "height": 10,
      "weight": 295,
      "type1": "bug",
      "type2": "grass",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/47.svg",
      "color": "red",
      "habitat": "forest"
    },
    {
      "id": 48,
      "name": "venonat",
      "height": 10,
      "weight": 300,
      "type1": "bug",
      "type2": "poison",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/48.svg",
      "color": "purple",
      "habitat": "forest"
    },
    {
      "id": 49,
      "name": "venomoth",
      "height": 15,
      "weight": 125,
      "type1": "bug",
      "type2": "poison",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/49.svg",
      "color": "purple",
      "habitat": "forest"
    },
    {
      "id": 50,
      "name": "diglett",
      "height": 2,
      "weight": 8,
      "type1": "ground",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/50.svg",
      "color": "brown",
      "habitat": "cave"
    },
    {
      "id": 51,
      "name": "dugtrio",
      "height": 7,
      "weight": 333,
      "type1": "ground",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/51.svg",
      "color": "brown",
      "habitat": "cave"
    },
    {
      "id": 52,
      "name": "meowth",
      "height": 4,
      "weight": 42,
      "type1": "normal",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/52.svg",
      "color": "yellow",
      "habitat": "urban"
    },
    {
      "id": 53,
      "name": "persian",
      "height": 10,
      "weight": 320,
      "type1": "normal",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/53.svg",
      "color": "yellow",
      "habitat": "urban"
    },
    {
      "id": 54,
      "name": "psyduck",
      "height": 8,
      "weight": 196,
      "type1": "water",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/54.svg",
      "color": "yellow",
      "habitat": "waters-edge"
    },
    {
      "id": 55,
      "name": "golduck",
      "height": 17,
      "weight": 766,
      "type1": "water",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/55.svg",
      "color": "blue",
      "habitat": "waters-edge"
    },
    {
      "id": 56,
      "name": "mankey",
      "height": 5,
      "weight": 280,
      "type1": "fighting",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/56.svg",
      "color": "brown",
      "habitat": "mountain"
    },
    {
      "id": 57,
      "name": "primeape",
      "height": 10,
      "weight": 320,
      "type1": "fighting",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/57.svg",
      "color": "brown",
      "habitat": "mountain"
    },
    {
      "id": 58,
      "name": "growlithe",
      "height": 7,
      "weight": 190,
      "type1": "fire",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/58.svg",
      "color": "brown",
      "habitat": "grassland"
    },
    {
      "id": 59,
      "name": "arcanine",
      "height": 19,
      "weight": 1550,
      "type1": "fire",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/59.svg",
      "color": "brown",
      "habitat": "grassland"
    },
    {
      "id": 60,
      "name": "poliwag",
      "height": 6,
      "weight": 124,
      "type1": "water",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/60.svg",
      "color": "blue",
      "habitat": "waters-edge"
    },
    {
      "id": 61,
      "name": "poliwhirl",
      "height": 10,
      "weight": 200,
      "type1": "water",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/61.svg",
      "color": "blue",
      "habitat": "waters-edge"
    },
    {
      "id": 62,
      "name": "poliwrath",
      "height": 13,
      "weight": 540,
      "type1": "water",
      "type2": "fighting",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/62.svg",
      "color": "blue",
      "habitat": "waters-edge"
    },
    {
      "id": 63,
      "name": "abra",
      "height": 9,
      "weight": 195,
      "type1": "psychic",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/63.svg",
      "color": "brown",
      "habitat": "urban"
    },
    {
      "id": 64,
      "name": "kadabra",
      "height": 13,
      "weight": 565,
      "type1": "psychic",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/64.svg",
      "color": "brown",
      "habitat": "urban"
    },
    {
      "id": 65,
      "name": "alakazam",
      "height": 15,
      "weight": 480,
      "type1": "psychic",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/65.svg",
      "color": "brown",
      "habitat": "urban"
    },
    {
      "id": 66,
      "name": "machop",
      "height": 8,
      "weight": 195,
      "type1": "fighting",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/66.svg",
      "color": "gray",
      "habitat": "mountain"
    },
    {
      "id": 67,
      "name": "machoke",
      "height": 15,
      "weight": 705,
      "type1": "fighting",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/67.svg",
      "color": "gray",
      "habitat": "mountain"
    },
    {
      "id": 68,
      "name": "machamp",
      "height": 16,
      "weight": 1300,
      "type1": "fighting",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/68.svg",
      "color": "gray",
      "habitat": "mountain"
    },
    {
      "id": 69,
      "name": "bellsprout",
      "height": 7,
      "weight": 40,
      "type1": "grass",
      "type2": "poison",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/69.svg",
      "color": "green",
      "habitat": "forest"
    },
    {
      "id": 70,
      "name": "weepinbell",
      "height": 10,
      "weight": 64,
      "type1": "grass",
      "type2": "poison",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/70.svg",
      "color": "green",
      "habitat": "forest"
    },
    {
      "id": 71,
      "name": "victreebel",
      "height": 17,
      "weight": 155,
      "type1": "grass",
      "type2": "poison",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/71.svg",
      "color": "green",
      "habitat": "forest"
    },
    {
      "id": 72,
      "name": "tentacool",
      "height": 9,
      "weight": 455,
      "type1": "water",
      "type2": "poison",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/72.svg",
      "color": "blue",
      "habitat": "sea"
    },
    {
      "id": 73,
      "name": "tentacruel",
      "height": 16,
      "weight": 550,
      "type1": "water",
      "type2": "poison",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/73.svg",
      "color": "blue",
      "habitat": "sea"
    },
    {
      "id": 74,
      "name": "geodude",
      "height": 4,
      "weight": 200,
      "type1": "rock",
      "type2": "ground",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/74.svg",
      "color": "brown",
      "habitat": "mountain"
    },
    {
      "id": 75,
      "name": "graveler",
      "height": 10,
      "weight": 1050,
      "type1": "rock",
      "type2": "ground",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/75.svg",
      "color": "brown",
      "habitat": "mountain"
    },
    {
      "id": 76,
      "name": "golem",
      "height": 14,
      "weight": 3000,
      "type1": "rock",
      "type2": "ground",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/76.svg",
      "color": "brown",
      "habitat": "mountain"
    },
    {
      "id": 77,
      "name": "ponyta",
      "height": 10,
      "weight": 300,
      "type1": "fire",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/77.svg",
      "color": "yellow",
      "habitat": "grassland"
    },
    {
      "id": 78,
      "name": "rapidash",
      "height": 17,
      "weight": 950,
      "type1": "fire",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/78.svg",
      "color": "yellow",
      "habitat": "grassland"
    },
    {
      "id": 79,
      "name": "slowpoke",
      "height": 12,
      "weight": 360,
      "type1": "water",
      "type2": "psychic",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/79.svg",
      "color": "pink",
      "habitat": "waters-edge"
    },
    {
      "id": 80,
      "name": "slowbro",
      "height": 16,
      "weight": 785,
      "type1": "water",
      "type2": "psychic",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/80.svg",
      "color": "pink",
      "habitat": "waters-edge"
    },
    {
      "id": 81,
      "name": "magnemite",
      "height": 3,
      "weight": 60,
      "type1": "electric",
      "type2": "steel",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/81.svg",
      "color": "gray",
      "habitat": "rough-terrain"
    },
    {
      "id": 82,
      "name": "magneton",
      "height": 10,
      "weight": 600,
      "type1": "electric",
      "type2": "steel",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/82.svg",
      "color": "gray",
      "habitat": "rough-terrain"
    },
    {
      "id": 83,
      "name": "farfetchd",
      "height": 8,
      "weight": 150,
      "type1": "normal",
      "type2": "flying",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/83.svg",
      "color": "brown",
      "habitat": "grassland"
    },
    {
      "id": 84,
      "name": "doduo",
      "height": 14,
      "weight": 392,
      "type1": "normal",
      "type2": "flying",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/84.svg",
      "color": "brown",
      "habitat": "grassland"
    },
    {
      "id": 85,
      "name": "dodrio",
      "height": 18,
      "weight": 852,
      "type1": "normal",
      "type2": "flying",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/85.svg",
      "color": "brown",
      "habitat": "grassland"
    },
    {
      "id": 86,
      "name": "seel",
      "height": 11,
      "weight": 900,
      "type1": "water",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/86.svg",
      "color": "white",
      "habitat": "sea"
    },
    {
      "id": 87,
      "name": "dewgong",
      "height": 17,
      "weight": 1200,
      "type1": "water",
      "type2": "ice",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/87.svg",
      "color": "white",
      "habitat": "sea"
    },
    {
      "id": 88,
      "name": "grimer",
      "height": 9,
      "weight": 300,
      "type1": "poison",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/88.svg",
      "color": "purple",
      "habitat": "urban"
    },
    {
      "id": 89,
      "name": "muk",
      "height": 12,
      "weight": 300,
      "type1": "poison",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/89.svg",
      "color": "purple",
      "habitat": "urban"
    },
    {
      "id": 90,
      "name": "shellder",
      "height": 3,
      "weight": 40,
      "type1": "water",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/90.svg",
      "color": "purple",
      "habitat": "sea"
    },
    {
      "id": 91,
      "name": "cloyster",
      "height": 15,
      "weight": 1325,
      "type1": "water",
      "type2": "ice",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/91.svg",
      "color": "purple",
      "habitat": "sea"
    },
    {
      "id": 92,
      "name": "gastly",
      "height": 13,
      "weight": 1,
      "type1": "ghost",
      "type2": "poison",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/92.svg",
      "color": "purple",
      "habitat": "cave"
    },
    {
      "id": 93,
      "name": "haunter",
      "height": 16,
      "weight": 1,
      "type1": "ghost",
      "type2": "poison",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/93.svg",
      "color": "purple",
      "habitat": "cave"
    },
    {
      "id": 94,
      "name": "gengar",
      "height": 15,
      "weight": 405,
      "type1": "ghost",
      "type2": "poison",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/94.svg",
      "color": "purple",
      "habitat": "cave"
    },
    {
      "id": 95,
      "name": "onix",
      "height": 88,
      "weight": 2100,
      "type1": "rock",
      "type2": "ground",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/95.svg",
      "color": "gray",
      "habitat": "cave"
    },
    {
      "id": 96,
      "name": "drowzee",
      "height": 10,
      "weight": 324,
      "type1": "psychic",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/96.svg",
      "color": "yellow",
      "habitat": "grassland"
    },
    {
      "id": 97,
      "name": "hypno",
      "height": 16,
      "weight": 756,
      "type1": "psychic",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/97.svg",
      "color": "yellow",
      "habitat": "grassland"
    },
    {
      "id": 98,
      "name": "krabby",
      "height": 4,
      "weight": 65,
      "type1": "water",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/98.svg",
      "color": "red",
      "habitat": "waters-edge"
    },
    {
      "id": 99,
      "name": "kingler",
      "height": 13,
      "weight": 600,
      "type1": "water",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/99.svg",
      "color": "red",
      "habitat": "waters-edge"
    },
    {
      "id": 100,
      "name": "voltorb",
      "height": 5,
      "weight": 104,
      "type1": "electric",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/100.svg",
      "color": "red",
      "habitat": "urban"
    },
    {
      "id": 101,
      "name": "electrode",
      "height": 12,
      "weight": 666,
      "type1": "electric",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/101.svg",
      "color": "red",
      "habitat": "urban"
    },
    {
      "id": 102,
      "name": "exeggcute",
      "height": 4,
      "weight": 25,
      "type1": "grass",
      "type2": "psychic",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/102.svg",
      "color": "pink",
      "habitat": "forest"
    },
    {
      "id": 103,
      "name": "exeggutor",
      "height": 20,
      "weight": 1200,
      "type1": "grass",
      "type2": "psychic",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/103.svg",
      "color": "yellow",
      "habitat": "forest"
    },
    {
      "id": 104,
      "name": "cubone",
      "height": 4,
      "weight": 65,
      "type1": "ground",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/104.svg",
      "color": "brown",
      "habitat": "mountain"
    },
    {
      "id": 105,
      "name": "marowak",
      "height": 10,
      "weight": 450,
      "type1": "ground",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/105.svg",
      "color": "brown",
      "habitat": "mountain"
    },
    {
      "id": 106,
      "name": "hitmonlee",
      "height": 15,
      "weight": 498,
      "type1": "fighting",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/106.svg",
      "color": "brown",
      "habitat": "urban"
    },
    {
      "id": 107,
      "name": "hitmonchan",
      "height": 14,
      "weight": 502,
      "type1": "fighting",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/107.svg",
      "color": "brown",
      "habitat": "urban"
    },
    {
      "id": 108,
      "name": "lickitung",
      "height": 12,
      "weight": 655,
      "type1": "normal",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/108.svg",
      "color": "pink",
      "habitat": "grassland"
    },
    {
      "id": 109,
      "name": "koffing",
      "height": 6,
      "weight": 10,
      "type1": "poison",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/109.svg",
      "color": "purple",
      "habitat": "urban"
    },
    {
      "id": 110,
      "name": "weezing",
      "height": 12,
      "weight": 95,
      "type1": "poison",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/110.svg",
      "color": "purple",
      "habitat": "urban"
    },
    {
      "id": 111,
      "name": "rhyhorn",
      "height": 10,
      "weight": 1150,
      "type1": "ground",
      "type2": "rock",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/111.svg",
      "color": "gray",
      "habitat": "rough-terrain"
    },
    {
      "id": 112,
      "name": "rhydon",
      "height": 19,
      "weight": 1200,
      "type1": "ground",
      "type2": "rock",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/112.svg",
      "color": "gray",
      "habitat": "rough-terrain"
    },
    {
      "id": 113,
      "name": "chansey",
      "height": 11,
      "weight": 346,
      "type1": "normal",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/113.svg",
      "color": "pink",
      "habitat": "urban"
    },
    {
      "id": 114,
      "name": "tangela",
      "height": 10,
      "weight": 350,
      "type1": "grass",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/114.svg",
      "color": "blue",
      "habitat": "grassland"
    },
    {
      "id": 115,
      "name": "kangaskhan",
      "height": 22,
      "weight": 800,
      "type1": "normal",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/115.svg",
      "color": "brown",
      "habitat": "grassland"
    },
    {
      "id": 116,
      "name": "horsea",
      "height": 4,
      "weight": 80,
      "type1": "water",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/116.svg",
      "color": "blue",
      "habitat": "sea"
    },
    {
      "id": 117,
      "name": "seadra",
      "height": 12,
      "weight": 250,
      "type1": "water",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/117.svg",
      "color": "blue",
      "habitat": "sea"
    },
    {
      "id": 118,
      "name": "goldeen",
      "height": 6,
      "weight": 150,
      "type1": "water",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/118.svg",
      "color": "red",
      "habitat": "waters-edge"
    },
    {
      "id": 119,
      "name": "seaking",
      "height": 13,
      "weight": 390,
      "type1": "water",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/119.svg",
      "color": "red",
      "habitat": "waters-edge"
    },
    {
      "id": 120,
      "name": "staryu",
      "height": 8,
      "weight": 345,
      "type1": "water",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/120.svg",
      "color": "brown",
      "habitat": "sea"
    },
    {
      "id": 121,
      "name": "starmie",
      "height": 11,
      "weight": 800,
      "type1": "water",
      "type2": "psychic",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/121.svg",
      "color": "purple",
      "habitat": "sea"
    },
    {
      "id": 122,
      "name": "mr-mime",
      "height": 13,
      "weight": 545,
      "type1": "psychic",
      "type2": "fairy",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/122.svg",
      "color": "pink",
      "habitat": "urban"
    },
    {
      "id": 123,
      "name": "scyther",
      "height": 15,
      "weight": 560,
      "type1": "bug",
      "type2": "flying",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/123.svg",
      "color": "green",
      "habitat": "grassland"
    },
    {
      "id": 124,
      "name": "jynx",
      "height": 14,
      "weight": 406,
      "type1": "ice",
      "type2": "psychic",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/124.svg",
      "color": "red",
      "habitat": "urban"
    },
    {
      "id": 125,
      "name": "electabuzz",
      "height": 11,
      "weight": 300,
      "type1": "electric",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/125.svg",
      "color": "yellow",
      "habitat": "grassland"
    },
    {
      "id": 126,
      "name": "magmar",
      "height": 13,
      "weight": 445,
      "type1": "fire",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/126.svg",
      "color": "red",
      "habitat": "mountain"
    },
    {
      "id": 127,
      "name": "pinsir",
      "height": 15,
      "weight": 550,
      "type1": "bug",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/127.svg",
      "color": "brown",
      "habitat": "forest"
    },
    {
      "id": 128,
      "name": "tauros",
      "height": 14,
      "weight": 884,
      "type1": "normal",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/128.svg",
      "color": "brown",
      "habitat": "grassland"
    },
    {
      "id": 129,
      "name": "magikarp",
      "height": 9,
      "weight": 100,
      "type1": "water",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/129.svg",
      "color": "red",
      "habitat": "waters-edge"
    },
    {
      "id": 130,
      "name": "gyarados",
      "height": 65,
      "weight": 2350,
      "type1": "water",
      "type2": "flying",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/130.svg",
      "color": "blue",
      "habitat": "waters-edge"
    },
    {
      "id": 131,
      "name": "lapras",
      "height": 25,
      "weight": 2200,
      "type1": "water",
      "type2": "ice",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/131.svg",
      "color": "blue",
      "habitat": "sea"
    },
    {
      "id": 132,
      "name": "ditto",
      "height": 3,
      "weight": 40,
      "type1": "normal",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/132.svg",
      "color": "purple",
      "habitat": "urban"
    },
    {
      "id": 133,
      "name": "eevee",
      "height": 3,
      "weight": 65,
      "type1": "normal",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/133.svg",
      "color": "brown",
      "habitat": "urban"
    },
    {
      "id": 134,
      "name": "vaporeon",
      "height": 10,
      "weight": 290,
      "type1": "water",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/134.svg",
      "color": "blue",
      "habitat": "urban"
    },
    {
      "id": 135,
      "name": "jolteon",
      "height": 8,
      "weight": 245,
      "type1": "electric",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/135.svg",
      "color": "yellow",
      "habitat": "urban"
    },
    {
      "id": 136,
      "name": "flareon",
      "height": 9,
      "weight": 250,
      "type1": "fire",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/136.svg",
      "color": "red",
      "habitat": "urban"
    },
    {
      "id": 137,
      "name": "porygon",
      "height": 8,
      "weight": 365,
      "type1": "normal",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/137.svg",
      "color": "pink",
      "habitat": "urban"
    },
    {
      "id": 138,
      "name": "omanyte",
      "height": 4,
      "weight": 75,
      "type1": "rock",
      "type2": "water",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/138.svg",
      "color": "blue",
      "habitat": "sea"
    },
    {
      "id": 139,
      "name": "omastar",
      "height": 10,
      "weight": 350,
      "type1": "rock",
      "type2": "water",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/139.svg",
      "color": "blue",
      "habitat": "sea"
    },
    {
      "id": 140,
      "name": "kabuto",
      "height": 5,
      "weight": 115,
      "type1": "rock",
      "type2": "water",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/140.svg",
      "color": "brown",
      "habitat": "sea"
    },
    {
      "id": 141,
      "name": "kabutops",
      "height": 13,
      "weight": 405,
      "type1": "rock",
      "type2": "water",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/141.svg",
      "color": "brown",
      "habitat": "sea"
    },
    {
      "id": 142,
      "name": "aerodactyl",
      "height": 18,
      "weight": 590,
      "type1": "rock",
      "type2": "flying",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/142.svg",
      "color": "purple",
      "habitat": "mountain"
    },
    {
      "id": 143,
      "name": "snorlax",
      "height": 21,
      "weight": 4600,
      "type1": "normal",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/143.svg",
      "color": "black",
      "habitat": "mountain"
    },
    {
      "id": 144,
      "name": "articuno",
      "height": 17,
      "weight": 554,
      "type1": "ice",
      "type2": "flying",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/144.svg",
      "color": "blue",
      "habitat": "rare"
    },
    {
      "id": 145,
      "name": "zapdos",
      "height": 16,
      "weight": 526,
      "type1": "electric",
      "type2": "flying",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/145.svg",
      "color": "yellow",
      "habitat": "rare"
    },
    {
      "id": 146,
      "name": "moltres",
      "height": 20,
      "weight": 600,
      "type1": "fire",
      "type2": "flying",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/146.svg",
      "color": "yellow",
      "habitat": "rare"
    },
    {
      "id": 147,
      "name": "dratini",
      "height": 18,
      "weight": 33,
      "type1": "dragon",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/147.svg",
      "color": "blue",
      "habitat": "waters-edge"
    },
    {
      "id": 148,
      "name": "dragonair",
      "height": 40,
      "weight": 165,
      "type1": "dragon",
      "type2": null,
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/148.svg",
      "color": "blue",
      "habitat": "waters-edge"
    },
    {
      "id": 149,
      "name": "dragonite",
      "height": 22,
      "weight": 2100,
      "type1": "dragon",
      "type2": "flying",
      "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/149.svg",
      "color": "brown",
      "habitat": "waters-edge"
    }
  ];

  export default mockPokemonAttributes;
